var bankName;
console.log("Before initialization:",bankName);
var typeOfBankName= typeof bankName;
console.log("Type of Bank name is:",typeOfBankName);
var bankName="SBI Bank";
console.log("After initialization:", bankName);
var typeOfBankName= typeof bankName;
console.log("Type of Bank name is:",typeOfBankName);
var marks="90%";
console.log("Marks:", marks);
var typeOfMarks=typeof marks;
console.log("Type of marks is:",typeOfMarks);
var isWorking; 
console.log("Before initialization isWorking:",isWorking);
var isWorking="true";
console.log("After initialization isWorking:",isWorking);
var totalCount="Hundred and seven";
console.log("Total count:",totalCount);
var typeOfTotalCount= typeof totalCount;
console.log("Type of Total count:",typeOfTotalCount);
totalCount=107;
console.log("New value:",totalCount);
console.log("Type of Total count:", typeof totalCount);